-- CreateTable
CREATE TABLE "contratos_compra_cafe" (
    "id" TEXT NOT NULL,
    "numeroContrato" TEXT NOT NULL,
    "dataContrato" DATE NOT NULL,
    "tipoOperacao" TEXT NOT NULL DEFAULT 'FÍSICO',
    "modalidade" TEXT NOT NULL DEFAULT 'POSTO',
    "referenciaPagamento" TEXT NOT NULL,
    "codigoVendedor" TEXT NOT NULL,
    "nomeVendedor" TEXT NOT NULL,
    "cnpjVendedor" TEXT NOT NULL,
    "enderecoVendedor" TEXT NOT NULL,
    "inscricaoEstadualVendedor" TEXT NOT NULL,
    "grupoVendedor" TEXT NOT NULL,
    "corretor" TEXT NOT NULL,
    "comissaoCorretor" DECIMAL(6,2) NOT NULL DEFAULT 0,
    "agente" TEXT NOT NULL,
    "comissaoAgente" DECIMAL(6,2) NOT NULL DEFAULT 0,
    "descricaoProduto" TEXT NOT NULL,
    "safra" TEXT NOT NULL,
    "padrao" TEXT NOT NULL,
    "bebida" TEXT NOT NULL,
    "tipoEmbalagem" TEXT NOT NULL,
    "valorLivrePorSaca" DECIMAL(18,2) NOT NULL,
    "quantidadeSacas" INTEGER NOT NULL,
    "valorFaturadoPorSaca" DECIMAL(18,2) NOT NULL,
    "creditoIcms" TEXT NOT NULL,
    "condicaoPagamento" TEXT NOT NULL,
    "banco" TEXT NOT NULL,
    "agencia" TEXT NOT NULL,
    "conta" TEXT NOT NULL,
    "observacoes" TEXT NOT NULL,
    "localRetirada" TEXT NOT NULL,
    "codigoLocalEntrega" TEXT NOT NULL,
    "previsaoEntrega" DATE,
    "nomeLocalEntrega" TEXT NOT NULL,
    "cnpjLocalEntrega" TEXT NOT NULL,
    "enderecoLocalEntrega" TEXT NOT NULL,
    "cidadeLocalEntrega" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "contratos_compra_cafe_pkey" PRIMARY KEY ("id")
);
