// Lista de paises com o id numerico ISO 3166-1 e o nome em ingles usados pelo
// dataset do mapa (world-atlas/countries-110m.json), mais o rotulo em
// portugues exibido no formulario. O campo Sale.country guarda o `id` (nao o
// nome livre) para o mapa em world-map.tsx conseguir casar com precisao.
export type Continent = "África" | "América" | "Ásia" | "Europa" | "Oceania";

export const CONTINENTS: Continent[] = ["América", "Europa", "África", "Ásia", "Oceania"];

export type CountryOption = { id: string; nameEn: string; labelPt: string; continent: Continent };

const COUNTRIES_UNSORTED: CountryOption[] = [
  { id: "004", nameEn: "Afghanistan", labelPt: "Afeganistão", continent: "Ásia" },
  { id: "008", nameEn: "Albania", labelPt: "Albânia", continent: "Europa" },
  { id: "012", nameEn: "Algeria", labelPt: "Argélia", continent: "África" },
  { id: "024", nameEn: "Angola", labelPt: "Angola", continent: "África" },
  { id: "032", nameEn: "Argentina", labelPt: "Argentina", continent: "América" },
  { id: "051", nameEn: "Armenia", labelPt: "Armênia", continent: "Ásia" },
  { id: "036", nameEn: "Australia", labelPt: "Austrália", continent: "Oceania" },
  { id: "040", nameEn: "Austria", labelPt: "Áustria", continent: "Europa" },
  { id: "031", nameEn: "Azerbaijan", labelPt: "Azerbaijão", continent: "Ásia" },
  { id: "044", nameEn: "Bahamas", labelPt: "Bahamas", continent: "América" },
  { id: "050", nameEn: "Bangladesh", labelPt: "Bangladesh", continent: "Ásia" },
  { id: "112", nameEn: "Belarus", labelPt: "Bielorrússia", continent: "Europa" },
  { id: "056", nameEn: "Belgium", labelPt: "Bélgica", continent: "Europa" },
  { id: "084", nameEn: "Belize", labelPt: "Belize", continent: "América" },
  { id: "204", nameEn: "Benin", labelPt: "Benin", continent: "África" },
  { id: "064", nameEn: "Bhutan", labelPt: "Butão", continent: "Ásia" },
  { id: "068", nameEn: "Bolivia", labelPt: "Bolívia", continent: "América" },
  { id: "070", nameEn: "Bosnia and Herz.", labelPt: "Bósnia e Herzegovina", continent: "Europa" },
  { id: "072", nameEn: "Botswana", labelPt: "Botsuana", continent: "África" },
  { id: "076", nameEn: "Brazil", labelPt: "Brasil", continent: "América" },
  { id: "096", nameEn: "Brunei", labelPt: "Brunei", continent: "Ásia" },
  { id: "100", nameEn: "Bulgaria", labelPt: "Bulgária", continent: "Europa" },
  { id: "854", nameEn: "Burkina Faso", labelPt: "Burquina Faso", continent: "África" },
  { id: "108", nameEn: "Burundi", labelPt: "Burundi", continent: "África" },
  { id: "116", nameEn: "Cambodia", labelPt: "Camboja", continent: "Ásia" },
  { id: "120", nameEn: "Cameroon", labelPt: "Camarões", continent: "África" },
  { id: "124", nameEn: "Canada", labelPt: "Canadá", continent: "América" },
  { id: "140", nameEn: "Central African Rep.", labelPt: "República Centro-Africana", continent: "África" },
  { id: "148", nameEn: "Chad", labelPt: "Chade", continent: "África" },
  { id: "152", nameEn: "Chile", labelPt: "Chile", continent: "América" },
  { id: "156", nameEn: "China", labelPt: "China", continent: "Ásia" },
  { id: "170", nameEn: "Colombia", labelPt: "Colômbia", continent: "América" },
  { id: "178", nameEn: "Congo", labelPt: "Congo", continent: "África" },
  { id: "188", nameEn: "Costa Rica", labelPt: "Costa Rica", continent: "América" },
  { id: "384", nameEn: "Côte d'Ivoire", labelPt: "Costa do Marfim", continent: "África" },
  { id: "191", nameEn: "Croatia", labelPt: "Croácia", continent: "Europa" },
  { id: "192", nameEn: "Cuba", labelPt: "Cuba", continent: "América" },
  { id: "196", nameEn: "Cyprus", labelPt: "Chipre", continent: "Europa" },
  { id: "203", nameEn: "Czechia", labelPt: "República Tcheca", continent: "Europa" },
  { id: "180", nameEn: "Dem. Rep. Congo", labelPt: "República Democrática do Congo", continent: "África" },
  { id: "208", nameEn: "Denmark", labelPt: "Dinamarca", continent: "Europa" },
  { id: "262", nameEn: "Djibouti", labelPt: "Djibuti", continent: "África" },
  { id: "214", nameEn: "Dominican Rep.", labelPt: "República Dominicana", continent: "América" },
  { id: "218", nameEn: "Ecuador", labelPt: "Equador", continent: "América" },
  { id: "818", nameEn: "Egypt", labelPt: "Egito", continent: "África" },
  { id: "222", nameEn: "El Salvador", labelPt: "El Salvador", continent: "América" },
  { id: "226", nameEn: "Eq. Guinea", labelPt: "Guiné Equatorial", continent: "África" },
  { id: "232", nameEn: "Eritrea", labelPt: "Eritreia", continent: "África" },
  { id: "233", nameEn: "Estonia", labelPt: "Estônia", continent: "Europa" },
  { id: "748", nameEn: "eSwatini", labelPt: "Essuatíni", continent: "África" },
  { id: "231", nameEn: "Ethiopia", labelPt: "Etiópia", continent: "África" },
  { id: "238", nameEn: "Falkland Is.", labelPt: "Ilhas Malvinas", continent: "América" },
  { id: "242", nameEn: "Fiji", labelPt: "Fiji", continent: "Oceania" },
  { id: "246", nameEn: "Finland", labelPt: "Finlândia", continent: "Europa" },
  { id: "250", nameEn: "France", labelPt: "França", continent: "Europa" },
  { id: "266", nameEn: "Gabon", labelPt: "Gabão", continent: "África" },
  { id: "270", nameEn: "Gambia", labelPt: "Gâmbia", continent: "África" },
  { id: "268", nameEn: "Georgia", labelPt: "Geórgia", continent: "Ásia" },
  { id: "276", nameEn: "Germany", labelPt: "Alemanha", continent: "Europa" },
  { id: "288", nameEn: "Ghana", labelPt: "Gana", continent: "África" },
  { id: "300", nameEn: "Greece", labelPt: "Grécia", continent: "Europa" },
  { id: "304", nameEn: "Greenland", labelPt: "Groenlândia", continent: "América" },
  { id: "320", nameEn: "Guatemala", labelPt: "Guatemala", continent: "América" },
  { id: "324", nameEn: "Guinea", labelPt: "Guiné", continent: "África" },
  { id: "624", nameEn: "Guinea-Bissau", labelPt: "Guiné-Bissau", continent: "África" },
  { id: "328", nameEn: "Guyana", labelPt: "Guiana", continent: "América" },
  { id: "332", nameEn: "Haiti", labelPt: "Haiti", continent: "América" },
  { id: "340", nameEn: "Honduras", labelPt: "Honduras", continent: "América" },
  { id: "348", nameEn: "Hungary", labelPt: "Hungria", continent: "Europa" },
  { id: "352", nameEn: "Iceland", labelPt: "Islândia", continent: "Europa" },
  { id: "356", nameEn: "India", labelPt: "Índia", continent: "Ásia" },
  { id: "360", nameEn: "Indonesia", labelPt: "Indonésia", continent: "Ásia" },
  { id: "364", nameEn: "Iran", labelPt: "Irã", continent: "Ásia" },
  { id: "368", nameEn: "Iraq", labelPt: "Iraque", continent: "Ásia" },
  { id: "372", nameEn: "Ireland", labelPt: "Irlanda", continent: "Europa" },
  { id: "376", nameEn: "Israel", labelPt: "Israel", continent: "Ásia" },
  { id: "380", nameEn: "Italy", labelPt: "Itália", continent: "Europa" },
  { id: "388", nameEn: "Jamaica", labelPt: "Jamaica", continent: "América" },
  { id: "392", nameEn: "Japan", labelPt: "Japão", continent: "Ásia" },
  { id: "400", nameEn: "Jordan", labelPt: "Jordânia", continent: "Ásia" },
  { id: "398", nameEn: "Kazakhstan", labelPt: "Cazaquistão", continent: "Ásia" },
  { id: "404", nameEn: "Kenya", labelPt: "Quênia", continent: "África" },
  { id: "414", nameEn: "Kuwait", labelPt: "Kuwait", continent: "Ásia" },
  { id: "417", nameEn: "Kyrgyzstan", labelPt: "Quirguistão", continent: "Ásia" },
  { id: "418", nameEn: "Laos", labelPt: "Laos", continent: "Ásia" },
  { id: "428", nameEn: "Latvia", labelPt: "Letônia", continent: "Europa" },
  { id: "422", nameEn: "Lebanon", labelPt: "Líbano", continent: "Ásia" },
  { id: "426", nameEn: "Lesotho", labelPt: "Lesoto", continent: "África" },
  { id: "430", nameEn: "Liberia", labelPt: "Libéria", continent: "África" },
  { id: "434", nameEn: "Libya", labelPt: "Líbia", continent: "África" },
  { id: "440", nameEn: "Lithuania", labelPt: "Lituânia", continent: "Europa" },
  { id: "442", nameEn: "Luxembourg", labelPt: "Luxemburgo", continent: "Europa" },
  { id: "807", nameEn: "Macedonia", labelPt: "Macedônia do Norte", continent: "Europa" },
  { id: "450", nameEn: "Madagascar", labelPt: "Madagascar", continent: "África" },
  { id: "454", nameEn: "Malawi", labelPt: "Malawi", continent: "África" },
  { id: "458", nameEn: "Malaysia", labelPt: "Malásia", continent: "Ásia" },
  { id: "466", nameEn: "Mali", labelPt: "Mali", continent: "África" },
  { id: "478", nameEn: "Mauritania", labelPt: "Mauritânia", continent: "África" },
  { id: "484", nameEn: "Mexico", labelPt: "México", continent: "América" },
  { id: "498", nameEn: "Moldova", labelPt: "Moldávia", continent: "Europa" },
  { id: "496", nameEn: "Mongolia", labelPt: "Mongólia", continent: "Ásia" },
  { id: "499", nameEn: "Montenegro", labelPt: "Montenegro", continent: "Europa" },
  { id: "504", nameEn: "Morocco", labelPt: "Marrocos", continent: "África" },
  { id: "508", nameEn: "Mozambique", labelPt: "Moçambique", continent: "África" },
  { id: "104", nameEn: "Myanmar", labelPt: "Mianmar", continent: "Ásia" },
  { id: "516", nameEn: "Namibia", labelPt: "Namíbia", continent: "África" },
  { id: "524", nameEn: "Nepal", labelPt: "Nepal", continent: "Ásia" },
  { id: "528", nameEn: "Netherlands", labelPt: "Países Baixos", continent: "Europa" },
  { id: "540", nameEn: "New Caledonia", labelPt: "Nova Caledônia", continent: "Oceania" },
  { id: "554", nameEn: "New Zealand", labelPt: "Nova Zelândia", continent: "Oceania" },
  { id: "558", nameEn: "Nicaragua", labelPt: "Nicarágua", continent: "América" },
  { id: "562", nameEn: "Niger", labelPt: "Níger", continent: "África" },
  { id: "566", nameEn: "Nigeria", labelPt: "Nigéria", continent: "África" },
  { id: "408", nameEn: "North Korea", labelPt: "Coreia do Norte", continent: "Ásia" },
  { id: "578", nameEn: "Norway", labelPt: "Noruega", continent: "Europa" },
  { id: "512", nameEn: "Oman", labelPt: "Omã", continent: "Ásia" },
  { id: "586", nameEn: "Pakistan", labelPt: "Paquistão", continent: "Ásia" },
  { id: "275", nameEn: "Palestine", labelPt: "Palestina", continent: "Ásia" },
  { id: "591", nameEn: "Panama", labelPt: "Panamá", continent: "América" },
  { id: "598", nameEn: "Papua New Guinea", labelPt: "Papua-Nova Guiné", continent: "Oceania" },
  { id: "600", nameEn: "Paraguay", labelPt: "Paraguai", continent: "América" },
  { id: "604", nameEn: "Peru", labelPt: "Peru", continent: "América" },
  { id: "608", nameEn: "Philippines", labelPt: "Filipinas", continent: "Ásia" },
  { id: "616", nameEn: "Poland", labelPt: "Polônia", continent: "Europa" },
  { id: "620", nameEn: "Portugal", labelPt: "Portugal", continent: "Europa" },
  { id: "630", nameEn: "Puerto Rico", labelPt: "Porto Rico", continent: "América" },
  { id: "634", nameEn: "Qatar", labelPt: "Catar", continent: "Ásia" },
  { id: "642", nameEn: "Romania", labelPt: "Romênia", continent: "Europa" },
  { id: "643", nameEn: "Russia", labelPt: "Rússia", continent: "Europa" },
  { id: "646", nameEn: "Rwanda", labelPt: "Ruanda", continent: "África" },
  { id: "728", nameEn: "S. Sudan", labelPt: "Sudão do Sul", continent: "África" },
  { id: "682", nameEn: "Saudi Arabia", labelPt: "Arábia Saudita", continent: "Ásia" },
  { id: "686", nameEn: "Senegal", labelPt: "Senegal", continent: "África" },
  { id: "688", nameEn: "Serbia", labelPt: "Sérvia", continent: "Europa" },
  { id: "694", nameEn: "Sierra Leone", labelPt: "Serra Leoa", continent: "África" },
  { id: "703", nameEn: "Slovakia", labelPt: "Eslováquia", continent: "Europa" },
  { id: "705", nameEn: "Slovenia", labelPt: "Eslovênia", continent: "Europa" },
  { id: "090", nameEn: "Solomon Is.", labelPt: "Ilhas Salomão", continent: "Oceania" },
  { id: "706", nameEn: "Somalia", labelPt: "Somália", continent: "África" },
  { id: "710", nameEn: "South Africa", labelPt: "África do Sul", continent: "África" },
  { id: "410", nameEn: "South Korea", labelPt: "Coreia do Sul", continent: "Ásia" },
  { id: "724", nameEn: "Spain", labelPt: "Espanha", continent: "Europa" },
  { id: "144", nameEn: "Sri Lanka", labelPt: "Sri Lanka", continent: "Ásia" },
  { id: "729", nameEn: "Sudan", labelPt: "Sudão", continent: "África" },
  { id: "740", nameEn: "Suriname", labelPt: "Suriname", continent: "América" },
  { id: "752", nameEn: "Sweden", labelPt: "Suécia", continent: "Europa" },
  { id: "756", nameEn: "Switzerland", labelPt: "Suíça", continent: "Europa" },
  { id: "760", nameEn: "Syria", labelPt: "Síria", continent: "Ásia" },
  { id: "158", nameEn: "Taiwan", labelPt: "Taiwan", continent: "Ásia" },
  { id: "762", nameEn: "Tajikistan", labelPt: "Tajiquistão", continent: "Ásia" },
  { id: "834", nameEn: "Tanzania", labelPt: "Tanzânia", continent: "África" },
  { id: "764", nameEn: "Thailand", labelPt: "Tailândia", continent: "Ásia" },
  { id: "626", nameEn: "Timor-Leste", labelPt: "Timor-Leste", continent: "Ásia" },
  { id: "768", nameEn: "Togo", labelPt: "Togo", continent: "África" },
  { id: "780", nameEn: "Trinidad and Tobago", labelPt: "Trinidad e Tobago", continent: "América" },
  { id: "788", nameEn: "Tunisia", labelPt: "Tunísia", continent: "África" },
  { id: "792", nameEn: "Turkey", labelPt: "Turquia", continent: "Ásia" },
  { id: "795", nameEn: "Turkmenistan", labelPt: "Turcomenistão", continent: "Ásia" },
  { id: "800", nameEn: "Uganda", labelPt: "Uganda", continent: "África" },
  { id: "804", nameEn: "Ukraine", labelPt: "Ucrânia", continent: "Europa" },
  { id: "784", nameEn: "United Arab Emirates", labelPt: "Emirados Árabes Unidos", continent: "Ásia" },
  { id: "826", nameEn: "United Kingdom", labelPt: "Reino Unido", continent: "Europa" },
  { id: "840", nameEn: "United States of America", labelPt: "Estados Unidos", continent: "América" },
  { id: "858", nameEn: "Uruguay", labelPt: "Uruguai", continent: "América" },
  { id: "860", nameEn: "Uzbekistan", labelPt: "Uzbequistão", continent: "Ásia" },
  { id: "548", nameEn: "Vanuatu", labelPt: "Vanuatu", continent: "Oceania" },
  { id: "862", nameEn: "Venezuela", labelPt: "Venezuela", continent: "América" },
  { id: "704", nameEn: "Vietnam", labelPt: "Vietnã", continent: "Ásia" },
  { id: "887", nameEn: "Yemen", labelPt: "Iêmen", continent: "Ásia" },
  { id: "894", nameEn: "Zambia", labelPt: "Zâmbia", continent: "África" },
  { id: "716", nameEn: "Zimbabwe", labelPt: "Zimbábue", continent: "África" },
];

export const COUNTRIES: CountryOption[] = [...COUNTRIES_UNSORTED].sort((a, b) =>
  a.labelPt.localeCompare(b.labelPt, "pt-BR")
);

export function countryLabel(id: string | null): string {
  if (!id) return "-";
  return COUNTRIES.find((c) => c.id === id)?.labelPt ?? id;
}

export function countryContinent(id: string | null): Continent | null {
  if (!id) return null;
  return COUNTRIES.find((c) => c.id === id)?.continent ?? null;
}
