// Lista de paises com o id numerico ISO 3166-1 e o nome em ingles usados pelo
// dataset do mapa (world-atlas/countries-110m.json), mais o rotulo em
// portugues exibido no formulario. O campo Sale.country guarda o `id` (nao o
// nome livre) para o mapa em world-map.tsx conseguir casar com precisao.
export type CountryOption = { id: string; nameEn: string; labelPt: string };

export const COUNTRIES: CountryOption[] = [
  { id: "004", nameEn: "Afghanistan", labelPt: "Afeganistão" },
  { id: "008", nameEn: "Albania", labelPt: "Albânia" },
  { id: "012", nameEn: "Algeria", labelPt: "Argélia" },
  { id: "024", nameEn: "Angola", labelPt: "Angola" },
  { id: "032", nameEn: "Argentina", labelPt: "Argentina" },
  { id: "051", nameEn: "Armenia", labelPt: "Armênia" },
  { id: "036", nameEn: "Australia", labelPt: "Austrália" },
  { id: "040", nameEn: "Austria", labelPt: "Áustria" },
  { id: "031", nameEn: "Azerbaijan", labelPt: "Azerbaijão" },
  { id: "044", nameEn: "Bahamas", labelPt: "Bahamas" },
  { id: "050", nameEn: "Bangladesh", labelPt: "Bangladesh" },
  { id: "112", nameEn: "Belarus", labelPt: "Bielorrússia" },
  { id: "056", nameEn: "Belgium", labelPt: "Bélgica" },
  { id: "084", nameEn: "Belize", labelPt: "Belize" },
  { id: "204", nameEn: "Benin", labelPt: "Benin" },
  { id: "064", nameEn: "Bhutan", labelPt: "Butão" },
  { id: "068", nameEn: "Bolivia", labelPt: "Bolívia" },
  { id: "070", nameEn: "Bosnia and Herz.", labelPt: "Bósnia e Herzegovina" },
  { id: "072", nameEn: "Botswana", labelPt: "Botsuana" },
  { id: "076", nameEn: "Brazil", labelPt: "Brasil" },
  { id: "096", nameEn: "Brunei", labelPt: "Brunei" },
  { id: "100", nameEn: "Bulgaria", labelPt: "Bulgária" },
  { id: "854", nameEn: "Burkina Faso", labelPt: "Burquina Faso" },
  { id: "108", nameEn: "Burundi", labelPt: "Burundi" },
  { id: "116", nameEn: "Cambodia", labelPt: "Camboja" },
  { id: "120", nameEn: "Cameroon", labelPt: "Camarões" },
  { id: "124", nameEn: "Canada", labelPt: "Canadá" },
  { id: "140", nameEn: "Central African Rep.", labelPt: "República Centro-Africana" },
  { id: "148", nameEn: "Chad", labelPt: "Chade" },
  { id: "152", nameEn: "Chile", labelPt: "Chile" },
  { id: "156", nameEn: "China", labelPt: "China" },
  { id: "170", nameEn: "Colombia", labelPt: "Colômbia" },
  { id: "178", nameEn: "Congo", labelPt: "Congo" },
  { id: "188", nameEn: "Costa Rica", labelPt: "Costa Rica" },
  { id: "384", nameEn: "Côte d'Ivoire", labelPt: "Costa do Marfim" },
  { id: "191", nameEn: "Croatia", labelPt: "Croácia" },
  { id: "192", nameEn: "Cuba", labelPt: "Cuba" },
  { id: "196", nameEn: "Cyprus", labelPt: "Chipre" },
  { id: "203", nameEn: "Czechia", labelPt: "República Tcheca" },
  { id: "180", nameEn: "Dem. Rep. Congo", labelPt: "República Democrática do Congo" },
  { id: "208", nameEn: "Denmark", labelPt: "Dinamarca" },
  { id: "262", nameEn: "Djibouti", labelPt: "Djibuti" },
  { id: "214", nameEn: "Dominican Rep.", labelPt: "República Dominicana" },
  { id: "218", nameEn: "Ecuador", labelPt: "Equador" },
  { id: "818", nameEn: "Egypt", labelPt: "Egito" },
  { id: "222", nameEn: "El Salvador", labelPt: "El Salvador" },
  { id: "226", nameEn: "Eq. Guinea", labelPt: "Guiné Equatorial" },
  { id: "232", nameEn: "Eritrea", labelPt: "Eritreia" },
  { id: "233", nameEn: "Estonia", labelPt: "Estônia" },
  { id: "748", nameEn: "eSwatini", labelPt: "Essuatíni" },
  { id: "231", nameEn: "Ethiopia", labelPt: "Etiópia" },
  { id: "238", nameEn: "Falkland Is.", labelPt: "Ilhas Malvinas" },
  { id: "242", nameEn: "Fiji", labelPt: "Fiji" },
  { id: "246", nameEn: "Finland", labelPt: "Finlândia" },
  { id: "250", nameEn: "France", labelPt: "França" },
  { id: "266", nameEn: "Gabon", labelPt: "Gabão" },
  { id: "270", nameEn: "Gambia", labelPt: "Gâmbia" },
  { id: "268", nameEn: "Georgia", labelPt: "Geórgia" },
  { id: "276", nameEn: "Germany", labelPt: "Alemanha" },
  { id: "288", nameEn: "Ghana", labelPt: "Gana" },
  { id: "300", nameEn: "Greece", labelPt: "Grécia" },
  { id: "304", nameEn: "Greenland", labelPt: "Groenlândia" },
  { id: "320", nameEn: "Guatemala", labelPt: "Guatemala" },
  { id: "324", nameEn: "Guinea", labelPt: "Guiné" },
  { id: "624", nameEn: "Guinea-Bissau", labelPt: "Guiné-Bissau" },
  { id: "328", nameEn: "Guyana", labelPt: "Guiana" },
  { id: "332", nameEn: "Haiti", labelPt: "Haiti" },
  { id: "340", nameEn: "Honduras", labelPt: "Honduras" },
  { id: "348", nameEn: "Hungary", labelPt: "Hungria" },
  { id: "352", nameEn: "Iceland", labelPt: "Islândia" },
  { id: "356", nameEn: "India", labelPt: "Índia" },
  { id: "360", nameEn: "Indonesia", labelPt: "Indonésia" },
  { id: "364", nameEn: "Iran", labelPt: "Irã" },
  { id: "368", nameEn: "Iraq", labelPt: "Iraque" },
  { id: "372", nameEn: "Ireland", labelPt: "Irlanda" },
  { id: "376", nameEn: "Israel", labelPt: "Israel" },
  { id: "380", nameEn: "Italy", labelPt: "Itália" },
  { id: "388", nameEn: "Jamaica", labelPt: "Jamaica" },
  { id: "392", nameEn: "Japan", labelPt: "Japão" },
  { id: "400", nameEn: "Jordan", labelPt: "Jordânia" },
  { id: "398", nameEn: "Kazakhstan", labelPt: "Cazaquistão" },
  { id: "404", nameEn: "Kenya", labelPt: "Quênia" },
  { id: "414", nameEn: "Kuwait", labelPt: "Kuwait" },
  { id: "417", nameEn: "Kyrgyzstan", labelPt: "Quirguistão" },
  { id: "418", nameEn: "Laos", labelPt: "Laos" },
  { id: "428", nameEn: "Latvia", labelPt: "Letônia" },
  { id: "422", nameEn: "Lebanon", labelPt: "Líbano" },
  { id: "426", nameEn: "Lesotho", labelPt: "Lesoto" },
  { id: "430", nameEn: "Liberia", labelPt: "Libéria" },
  { id: "434", nameEn: "Libya", labelPt: "Líbia" },
  { id: "440", nameEn: "Lithuania", labelPt: "Lituânia" },
  { id: "442", nameEn: "Luxembourg", labelPt: "Luxemburgo" },
  { id: "807", nameEn: "Macedonia", labelPt: "Macedônia do Norte" },
  { id: "450", nameEn: "Madagascar", labelPt: "Madagascar" },
  { id: "454", nameEn: "Malawi", labelPt: "Malawi" },
  { id: "458", nameEn: "Malaysia", labelPt: "Malásia" },
  { id: "466", nameEn: "Mali", labelPt: "Mali" },
  { id: "478", nameEn: "Mauritania", labelPt: "Mauritânia" },
  { id: "484", nameEn: "Mexico", labelPt: "México" },
  { id: "498", nameEn: "Moldova", labelPt: "Moldávia" },
  { id: "496", nameEn: "Mongolia", labelPt: "Mongólia" },
  { id: "499", nameEn: "Montenegro", labelPt: "Montenegro" },
  { id: "504", nameEn: "Morocco", labelPt: "Marrocos" },
  { id: "508", nameEn: "Mozambique", labelPt: "Moçambique" },
  { id: "104", nameEn: "Myanmar", labelPt: "Mianmar" },
  { id: "516", nameEn: "Namibia", labelPt: "Namíbia" },
  { id: "524", nameEn: "Nepal", labelPt: "Nepal" },
  { id: "528", nameEn: "Netherlands", labelPt: "Países Baixos" },
  { id: "540", nameEn: "New Caledonia", labelPt: "Nova Caledônia" },
  { id: "554", nameEn: "New Zealand", labelPt: "Nova Zelândia" },
  { id: "558", nameEn: "Nicaragua", labelPt: "Nicarágua" },
  { id: "562", nameEn: "Niger", labelPt: "Níger" },
  { id: "566", nameEn: "Nigeria", labelPt: "Nigéria" },
  { id: "408", nameEn: "North Korea", labelPt: "Coreia do Norte" },
  { id: "578", nameEn: "Norway", labelPt: "Noruega" },
  { id: "512", nameEn: "Oman", labelPt: "Omã" },
  { id: "586", nameEn: "Pakistan", labelPt: "Paquistão" },
  { id: "275", nameEn: "Palestine", labelPt: "Palestina" },
  { id: "591", nameEn: "Panama", labelPt: "Panamá" },
  { id: "598", nameEn: "Papua New Guinea", labelPt: "Papua-Nova Guiné" },
  { id: "600", nameEn: "Paraguay", labelPt: "Paraguai" },
  { id: "604", nameEn: "Peru", labelPt: "Peru" },
  { id: "608", nameEn: "Philippines", labelPt: "Filipinas" },
  { id: "616", nameEn: "Poland", labelPt: "Polônia" },
  { id: "620", nameEn: "Portugal", labelPt: "Portugal" },
  { id: "630", nameEn: "Puerto Rico", labelPt: "Porto Rico" },
  { id: "634", nameEn: "Qatar", labelPt: "Catar" },
  { id: "642", nameEn: "Romania", labelPt: "Romênia" },
  { id: "643", nameEn: "Russia", labelPt: "Rússia" },
  { id: "646", nameEn: "Rwanda", labelPt: "Ruanda" },
  { id: "728", nameEn: "S. Sudan", labelPt: "Sudão do Sul" },
  { id: "682", nameEn: "Saudi Arabia", labelPt: "Arábia Saudita" },
  { id: "686", nameEn: "Senegal", labelPt: "Senegal" },
  { id: "688", nameEn: "Serbia", labelPt: "Sérvia" },
  { id: "694", nameEn: "Sierra Leone", labelPt: "Serra Leoa" },
  { id: "703", nameEn: "Slovakia", labelPt: "Eslováquia" },
  { id: "705", nameEn: "Slovenia", labelPt: "Eslovênia" },
  { id: "090", nameEn: "Solomon Is.", labelPt: "Ilhas Salomão" },
  { id: "706", nameEn: "Somalia", labelPt: "Somália" },
  { id: "710", nameEn: "South Africa", labelPt: "África do Sul" },
  { id: "410", nameEn: "South Korea", labelPt: "Coreia do Sul" },
  { id: "724", nameEn: "Spain", labelPt: "Espanha" },
  { id: "144", nameEn: "Sri Lanka", labelPt: "Sri Lanka" },
  { id: "729", nameEn: "Sudan", labelPt: "Sudão" },
  { id: "740", nameEn: "Suriname", labelPt: "Suriname" },
  { id: "752", nameEn: "Sweden", labelPt: "Suécia" },
  { id: "756", nameEn: "Switzerland", labelPt: "Suíça" },
  { id: "760", nameEn: "Syria", labelPt: "Síria" },
  { id: "158", nameEn: "Taiwan", labelPt: "Taiwan" },
  { id: "762", nameEn: "Tajikistan", labelPt: "Tajiquistão" },
  { id: "834", nameEn: "Tanzania", labelPt: "Tanzânia" },
  { id: "764", nameEn: "Thailand", labelPt: "Tailândia" },
  { id: "626", nameEn: "Timor-Leste", labelPt: "Timor-Leste" },
  { id: "768", nameEn: "Togo", labelPt: "Togo" },
  { id: "780", nameEn: "Trinidad and Tobago", labelPt: "Trinidad e Tobago" },
  { id: "788", nameEn: "Tunisia", labelPt: "Tunísia" },
  { id: "792", nameEn: "Turkey", labelPt: "Turquia" },
  { id: "795", nameEn: "Turkmenistan", labelPt: "Turcomenistão" },
  { id: "800", nameEn: "Uganda", labelPt: "Uganda" },
  { id: "804", nameEn: "Ukraine", labelPt: "Ucrânia" },
  { id: "784", nameEn: "United Arab Emirates", labelPt: "Emirados Árabes Unidos" },
  { id: "826", nameEn: "United Kingdom", labelPt: "Reino Unido" },
  { id: "840", nameEn: "United States of America", labelPt: "Estados Unidos" },
  { id: "858", nameEn: "Uruguay", labelPt: "Uruguai" },
  { id: "860", nameEn: "Uzbekistan", labelPt: "Uzbequistão" },
  { id: "548", nameEn: "Vanuatu", labelPt: "Vanuatu" },
  { id: "862", nameEn: "Venezuela", labelPt: "Venezuela" },
  { id: "704", nameEn: "Vietnam", labelPt: "Vietnã" },
  { id: "887", nameEn: "Yemen", labelPt: "Iêmen" },
  { id: "894", nameEn: "Zambia", labelPt: "Zâmbia" },
  { id: "716", nameEn: "Zimbabwe", labelPt: "Zimbábue" },
].sort((a, b) => a.labelPt.localeCompare(b.labelPt, "pt-BR"));

export function countryLabel(id: string | null): string {
  if (!id) return "-";
  return COUNTRIES.find((c) => c.id === id)?.labelPt ?? id;
}
