-- CreateTable
CREATE TABLE "financial_statements" (
    "id" TEXT NOT NULL,
    "periodLabel" TEXT NOT NULL,
    "referenceDate" DATE NOT NULL,
    "periodDays" INTEGER NOT NULL,
    "sourceFileName" TEXT NOT NULL,
    "receitaBruta" DECIMAL(18,2) NOT NULL,
    "deducoes" DECIMAL(18,2) NOT NULL,
    "receitaLiquida" DECIMAL(18,2) NOT NULL,
    "cmv" DECIMAL(18,2) NOT NULL,
    "lucroBruto" DECIMAL(18,2) NOT NULL,
    "outrasReceitasOperacionais" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "despesasGerais" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "despesasComerciais" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "despesasTributarias" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "depreciacaoAmortizacao" DECIMAL(18,2) NOT NULL,
    "outrasDespesasOperacionais" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "resultadoAtividade" DECIMAL(18,2) NOT NULL,
    "receitasFinanceiras" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "despesasFinanceiras" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "variacaoCambial" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "resultadoNaoOperacional" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "impostoRenda" DECIMAL(18,2) NOT NULL,
    "participacoes" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "lucroLiquido" DECIMAL(18,2) NOT NULL,
    "caixaEquivalentes" DECIMAL(18,2) NOT NULL,
    "titulosValoresMobiliarios" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "contasReceberClientes" DECIMAL(18,2) NOT NULL,
    "estoques" DECIMAL(18,2) NOT NULL,
    "adiantamentoFornecedores" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "outrosAtivosOperacionaisCirc" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "outrosAtivosNaoOperacionaisCirc" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "contasReceberColigadas" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "investimentos" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "imobilizado" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "intangivel" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "outrosAtivosNaoCirculantes" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "fornecedores" DECIMAL(18,2) NOT NULL,
    "salariosEncargos" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "impostosContribuicoes" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "emprestimosCurtoPrazo" DECIMAL(18,2) NOT NULL,
    "irAPagar" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "emprestimosColigadasCP" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "dividendosAPagar" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "adiantamentosClientes" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "outrosPassivosCirc" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "emprestimosLongoPrazo" DECIMAL(18,2) NOT NULL,
    "outrosPassivosNaoCirc" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "capitalSocial" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "reservas" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "lucrosPrejuizosAcumulados" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "outrosResultadosAbrangentes" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "ativosMoedaEstrangeira" DECIMAL(18,2),
    "passivosMoedaEstrangeira" DECIMAL(18,2),
    "extractedRaw" JSONB NOT NULL,
    "aiInsights" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "financial_statements_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "financial_statements_referenceDate_key" ON "financial_statements"("referenceDate");
